- name: Update hostname
  ansible.builtin.hostname:
    name: "{{ hostname_hostname }}"
  register: hostname_changed

- name: Update /etc/hostname
  ansible.builtin.copy:
    content: "{{ hostname_hostname }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'
  register: hostname_file_changed

- name: Add records to hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - regexp: "127.0.0.1"
      line: "127.0.0.1 localhost.localdomain localhost"
    - regexp: "::1"
      line: "::1 ip6-localhost ip6-loopback"

- name: Remove conflicting records from hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ item.regexp }}"
    state: absent
  loop:
    - regexp: "127.0.1.1"

- name: Add external FQDN record to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: ".*{{ hostname_ip_address }}"
    line: "{{ hostname_ip_address }} {{ hostname_hostname }}{% if hostname_hostname != hostname_hostname_fqdn %} {{ hostname_hostname_fqdn }}{% endif %}"
  register: hostname_hosts_changed

- name: Re-gather facts after setting hostname
  ansible.builtin.setup:
  when: hostname_changed.changed or hostname_hosts_changed.changed or hostname_file_changed.changed
